/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package opciones;

import appfutbol.AppFutbol;
import dao.DaoArbitro;
import dao.DaoJugador;
import java.io.IOException;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Pablo
 */
public class Opcion8 extends javax.swing.JFrame {

    /*
    public static Date ParseFecha(String fecha){
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        Date fechaDate = null;
        try {
            fechaDate = formato.parse(fecha);
        }catch (ParseException ex){
            System.out.println(ex);
        }
        return fechaDate;
    }*/
    /**
     * Creates new form Opcion8
     */
    public Opcion8() {
        initComponents();
        //Para que al cerrar, no se cierre el programa (que es lo que hace por defecto
        setDefaultCloseOperation(javax.swing.JFrame.HIDE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel9 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Introduzca identificador de partido:");

        jLabel3.setText("Introduzca identificador de estadio:");

        jLabel4.setText("Introduzca fecha de partido:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2016", "2015", "2014" }));

        jLabel1.setText("/");

        jLabel5.setText("/");

        jLabel6.setText("Introduzca identificador de equipo 1:");

        jLabel7.setText("Introduzca identificador de equipo 2:");

        jLabel8.setText("Pulse si el partido es ida:");

        jToggleButton1.setText("Ida");

        jLabel9.setText("Introduzca goles de equipo 1:");

        jLabel10.setText("Introduzca goles de equipo 2:");

        jLabel11.setForeground(new java.awt.Color(255, 51, 0));

        jLabel12.setForeground(new java.awt.Color(255, 51, 0));

        jLabel13.setForeground(new java.awt.Color(255, 51, 0));

        jLabel14.setForeground(new java.awt.Color(255, 51, 0));

        jLabel15.setForeground(new java.awt.Color(255, 51, 0));

        jLabel16.setForeground(new java.awt.Color(255, 51, 0));

        jButton3.setText("Aceptar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField1)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jTextField2)
                                    .addComponent(jTextField3)
                                    .addComponent(jTextField4)
                                    .addComponent(jToggleButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField5)
                                    .addComponent(jTextField6)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(114, 114, 114)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(235, 235, 235)
                                .addComponent(jButton3)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addContainerGap(141, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int idpartido=0,idestadio=0,ideq1=0,ideq2=0,g1=-1,g2=-1;
        String fecha=null;
        Boolean ida=null, error=false;
        try{
            idpartido = Integer.parseInt(jTextField1.getText());
            jLabel12.setVisible(false);
        }catch(Exception e){
            jLabel12.setText("Error al introducir identificador de partido");
            jLabel12.setVisible(true);
            idpartido=0;idestadio=0;ideq1=0;ideq2=0;g1=-1;g2=-1;
            fecha=null;ida=null;
            //En el caso de que haya error, no muestro los árbitros para poder elegir
            error=true;
        }
        try{
            idestadio = Integer.parseInt(jTextField2.getText());
            jLabel11.setVisible(false);
        }catch(Exception e){
            jLabel11.setText("Error al introducir identificador de estadio");
            jLabel11.setVisible(true);
            idpartido=0;idestadio=0;ideq1=0;ideq2=0;g1=-1;g2=-1;
            fecha=null;ida=null;
            error=true;
        }
        try{
            ideq1 = Integer.parseInt(jTextField3.getText());
            jLabel13.setVisible(false);
        }catch(Exception e){
            jLabel13.setText("Error al introducir identificador de equipo 1");
            jLabel13.setVisible(true);
            idpartido=0;idestadio=0;ideq1=0;ideq2=0;g1=-1;g2=-1;
            fecha=null;ida=null;
            error=true;
        }
        try{
            ideq2 = Integer.parseInt(jTextField4.getText());
            jLabel14.setVisible(false);
        }catch(Exception e){
            jLabel14.setText("Error al introducir identificador de equipo 2");
            jLabel14.setVisible(true);
            idpartido=0;idestadio=0;ideq1=0;ideq2=0;g1=-1;g2=-1;
            fecha=null;ida=null;
            error=true;
        }
        try{
            g1 = Integer.parseInt(jTextField5.getText());
            jLabel15.setVisible(false);
        }catch(Exception e){
            jLabel15.setText("Error al introducir goles de equipo 1");
            jLabel15.setVisible(true);
            idpartido=0;idestadio=0;ideq1=0;ideq2=0;g1=-1;g2=-1;
            fecha=null;ida=null;
            error=true;
        }
        try{
            g2 = Integer.parseInt(jTextField6.getText());
            jLabel16.setVisible(false);
        }catch(Exception e){
            jLabel16.setText("Error al introducir identificador de partido");
            jLabel16.setVisible(true);
            idpartido=0;idestadio=0;ideq1=0;ideq2=0;g1=-1;g2=-1;
            fecha=null;ida=null;
            error=true;
        }
        try{
            ida = jToggleButton1.isSelected();
        }catch(Exception e){
            //No va a haber excepciones con este booleano
        }
        //Para fecha, se inicializa a cero todo
        int dia=0,mes=0,año=0;
        try{
            //Si se introduce la posición 0, será el día 1, por eso se suma 1
            int pos = jComboBox1.getSelectedIndex();
            dia = pos+1;
        }catch(Exception e){
            //No va a haber excepciones con esto
        }
        try{
            int po = jComboBox2.getSelectedIndex();
            mes = po+1;
        }catch(Exception e){
            //No va a haber excepciones con esto
        }
        try{
            int p = jComboBox3.getSelectedIndex();
            if(p==0){
                año=2016;
            }else if(p==1){
                año=2015;
            }else if(p==2){
                año=2014;
            }
        }catch(Exception e){
            //No va a haber excepciones con esto
        }
        fecha = dia + "/"+ mes + "/" + año;
        System.out.println("Fecha "+fecha);
        
        //Si el id de los dos equipos es distinto, y no hay error al introducir partido
        //y si tiene alguna variable los valores iniciales no lo introduzco para dar de alta
        if(ideq1!=ideq2&&error==false&&idpartido!=0&&idestadio!=0&&fecha!=null&&ideq1!=0&&ideq2!=0&&ida!=null&&g1!=-1&&g2!=-1){
            
            ///////////////////////////////
            //Inicializamos un array de árbitros vacío
            ArrayList <Integer> idarbitros = new ArrayList <Integer>();
            String id=null;
            
            DaoArbitro daoarb = new DaoArbitro();
            DaoJugador daojug = new DaoJugador();
            AppFutbol appfutbol = new AppFutbol();
            appfutbol.listarArbitros();
            //Repetimos el pedir árbitros hasta que se introduce 0
            do{
                try{
                    id = JOptionPane.showInputDialog("Introduce id de árbitro\n\n(0 para dejar de introducir árbitros):");
                    //se introduce id obtenido en la lista de identificador de árbitro
                    //Eliminamos elementos repetidos del vector de árbitros
                        
                    Boolean existe = daoarb.BuscarArbitro(Integer.parseInt(id));
                    if(existe){
                        idarbitros.add(Integer.parseInt(id));
                    }else{
                        if(!"0".equals(id)){
                            JOptionPane.showMessageDialog(null,"Árbitro no existe en la base de datos", "Error", JOptionPane.ERROR_MESSAGE);
                        }
                        
                    }
                }catch(NumberFormatException e){
                    //JOptionPane.showMessageDialog(null,"Identificador de árbitro incorrecto", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }while(!"0".equals(id));
            ////////////////////////////////
            System.out.println("Numero arbitros: "+ idarbitros.size());
            
            ///////////////////////////////
            //Inicializamos un array de árbitros vacío
            ArrayList <Integer> idjugadores = new ArrayList <Integer>();
            String idj=null;
            
            appfutbol.listarJugadores();
            //Repetimos el pedir árbitros hasta que se introduce 0
            do{
                try{
                    idj = JOptionPane.showInputDialog("Introduce id de jugador\n\n(0 para dejar de introducir árbitros):");
                    //se introduce id obtenido en la lista de identificador de árbitro
                    Boolean existe = daojug.BuscarJugador(Integer.parseInt(idj));
                    if(existe){
                        idjugadores.add(Integer.parseInt(idj));
                    }else{
                        if(!"0".equals(idj)){
                            JOptionPane.showMessageDialog(null,"Jugador no existe en la base de datos", "Error", JOptionPane.ERROR_MESSAGE);
                        }
                    }
                    
                }catch(NumberFormatException e){
                    //JOptionPane.showMessageDialog(null,"Identificador de jugador incorrecto", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }while(!"0".equals(idj));
            ////////////////////////////////
            System.out.println("Numero jugadores: "+ idjugadores.size());
            
            //Si la lista de arbitros no está vacía
            if(idarbitros.size()>0&&idjugadores.size()>0){
                System.out.println("Entrado");
                try {
                    appfutbol.AltaPartido(idpartido, idestadio, fecha, ideq1, ideq2, ida, g1, g2, idarbitros, idjugadores);
                } catch (IOException ex) {
                    Logger.getLogger(Opcion8.class.getName()).log(Level.SEVERE, null, ex);
                }
                /*TODO
                try {
                    //A cada partido se calculan las posiciones. Este mismo método se usa para mostrar todos los equipos (21)
                    appfutbol.CalcularPosicionesEquipos();
                } catch (SQLException ex) {
                    Logger.getLogger(Opcion8.class.getName()).log(Level.SEVERE, null, ex);
                }*/
            }else{
                JOptionPane.showMessageDialog(null,"No se ha introducido ningún árbitro o jugador", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }else{//Si el id de los equipos es el mismo
            JOptionPane.showMessageDialog(null,"Identificadores de equipos iguales", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Opcion8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Opcion8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Opcion8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Opcion8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Opcion8().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables


}
